name: "fmt"

on:
  push:
  pull_request:

jobs:
  fmt:
    name: gofmt
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: gofmt
      run: |
        if [ "$(gofmt -s -l pkg cmd | wc -l)" -gt 0 ]; then
          exit 1
        fi
