name: "fmt"

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          build-essential \
          libelf-dev \
          clang \
          gcc-multilib \
          llvm \
          zlib1g-dev \
          libelf-dev \
          linux-tools-generic \
          linux-tools-common \
          linux-headers-$(uname -r) \
          linux-tools-$(uname -r)

    - name: build
      run: |
        make build

  fmt:
    name: gofmt
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: gofmt
      run: |
        if [ "$(gofmt -s -l pkg cmd | wc -l)" -gt 0 ]; then
          exit 1
        fi
