name: Deploy documentation
on:
  push:
    branches:
      - master 

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.x

      - run: pip install mkdocs-material 

      - name: Configure git user
        run: |
          git config user.name "mrtc0"
          git config user.email "mrtc0@ssrf.in"

      - run: mkdocs gh-deploy --force
